# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FeatureScreenshotter
                                 A QGIS plugin
 This plugin automatically takes screenshots of every feature in a layer for you.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-25
        copyright            : (C) 2023 by Michael Boyce - Fetch Analytics
        email                : michael@fetchanalytics.ai
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FeatureScreenshotter class from file FeatureScreenshotter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .feature_screenshotter import FeatureScreenshotter
    return FeatureScreenshotter(iface)
